module.exports = {
  apps: [
    {
      name: 'barber-backend',
      script: 'dist/src/main.js',
      cwd: './packages/backend',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      error_file: './logs/backend-error.log',
      out_file: './logs/backend-out.log',
      log_file: './logs/backend-combined.log',
      time: true,
    },
    {
      name: 'barber-h5',
      script: 'npx',
      args: 'serve -s -l 3001 ./dist',
      cwd: './packages/h5-merchant',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'production',
        VITE_API_URL: 'http://localhost:3000',
      },
      error_file: './logs/h5-error.log',
      out_file: './logs/h5-out.log',
      log_file: './logs/h5-combined.log',
      time: true,
    },
    {
      name: 'barber-admin',
      script: 'npx',
      args: 'serve -s -l 3002 ./dist',
      cwd: './packages/admin-web',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'production',
        VITE_API_URL: 'http://localhost:3000',
      },
      error_file: './logs/admin-error.log',
      out_file: './logs/admin-out.log',
      log_file: './logs/admin-combined.log',
      time: true,
    },
  ],
};
